The courses page
324712/RestaurantGeorgeZuilen pull request #34
Opened 2021-11-17 14:11 UTC by Dani66864

Ik heb de courses pagina geprogrammeerd zodat ik de gekozen courses naar de database te sturen

2021-11-17 17:27 UTC, Mitchel requested changes
Ik heb opmerkingen geplaatst, graag hier even naar kijken.
Tevens bestaat de opdracht uit "Studenten moeten zich kunnen inschrijven voor een course", ik zie hier alleen front-end dat niet helemaal klopt en veranderingen die er niet horen.

2021-11-17 17:27 UTC, Mitchel commented on resources/views/app/courses/overview.blade.php
> +                    <div class="card" style="width: 18rem;">
Hoezo werk je met inline style? Terwijl we dit ook via CSS kunnen doen?

2021-11-17 17:27 UTC, Mitchel commented on resources/views/app/courses/overview.blade.php
> +                            <li class="list-group-item">Lessons-Chef:<span class="text-primary"> 5</span></li>
Hoezo komt dit niet uit de database?

2021-11-17 17:27 UTC, Mitchel commented on resources/views/app/courses/overview.blade.php
> +                            <li class="list-group-item">Lessons-Bartender<span class="text-primary"> 5</span></li>
Hoezo komt dit niet uit de database?

2021-11-17 17:27 UTC, Mitchel commented on resources/views/app/courses/overview.blade.php
> +                            <li class="list-group-item">Lessons-Waiter:<span class="text-primary"> 5</span></li>
Hoezo komt dit niet uit de database?

2021-11-17 17:27 UTC, Mitchel commented on resources/views/app/courses/overview.blade.php
> +                            <p class="card-text">Course for General.</p>
Hoezo komt dit niet uit de database?

2021-11-17 17:27 UTC, Mitchel commented on resources/views/app/courses/overview.blade.php
> +                            <h3><input type="text" name="General" value="General" style="border:none;outline: none"></h3>
Hoezo heb je hier een input gedaan? Tis plain text en je hoeft er niks te typen?

2021-11-17 17:27 UTC, Mitchel commented on resources/views/app/includes/navigation.blade.php
> +                <i class="fas fa-box"></i> Courses
moet zijn `fal fa-box fa-fw`.

2021-11-17 17:27 UTC, Mitchel commented on routes/web.php
> +Route::get('-+', [MadeController::class, 'index'])->name('made');
Hoezo heb je de get aangepast van de made page? Die was toch al goed? Nu heet de pagina `-+`

2021-11-17 17:27 UTC, Mitchel commented on vendor/composer/autoload_real.php
> +        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(\dirname(__FILE__)));
Hoezo heb je dit aangepast?!

2021-11-18 13:00 UTC, Dani66864 commented on resources/views/app/courses/overview.blade.php
> +                    <div class="card" style="width: 18rem;">
Ik heb dat voor het gemak gedaan en om even snel dat te doen zonder class of id te geven

2021-11-18 13:03 UTC, Dani66864 commented on resources/views/app/courses/overview.blade.php
> +                            <li class="list-group-item">Lessons-Bartender<span class="text-primary"> 5</span></li>
Ik ga dat proberen te fixen voor maandag en als het lukt niet dan ga ik aan hulp vragen maar ik ga mijn best doen om dat af  te ronden

2021-11-18 13:05 UTC, Dani66864 commented on resources/views/app/courses/overview.blade.php
> +                            <li class="list-group-item">Lessons-Waiter:<span class="text-primary"> 5</span></li>
Maar maandag had ik aan jou gevraagd om dat te gaan realiseren want ik heb basis kennis nog over de laravel farmework en ik weet niet hoe kan de data uit de database gaan halen dat is het valkuil maar ik ga mijn best doen om dat even voor maandag te realiseren

2021-11-18 13:05 UTC, Dani66864 commented on resources/views/app/courses/overview.blade.php
> +                            <h3><input type="text" name="General" value="General" style="border:none;outline: none"></h3>
Hoe kan ik data versturen naar de database zonder input te gebruiken? volgens mij dat is onmogelijk

2021-11-18 13:06 UTC, Dani66864 commented on resources/views/app/includes/navigation.blade.php
> +                <i class="fas fa-box"></i> Courses
Ik vind dat de icon van de navbar past niet met de cources daarom had ik dat vervangen

2021-11-18 13:08 UTC, Dani66864 commented on routes/web.php
> +Route::get('-+', [MadeController::class, 'index'])->name('made');
Dat heb ik niet zelf aangepast maar toen hadden wij maandag de folder opnieuw binnen behaald vanuit de githup is dat gebeuren

2021-11-18 13:08 UTC, Dani66864 commented on vendor/composer/autoload_real.php
> +        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(\dirname(__FILE__)));
Dat heb ik niet zelf aangepast maar toen hadden wij maandag de folder opnieuw binnen behaald vanuit de githup is dat gebeuren

2021-11-18 16:58 UTC, Mitchel commented on resources/views/app/courses/overview.blade.php
> +                    <div class="card" style="width: 18rem;">
Die widths zijn niet nodig, dat doe je al met je grid (`col-sm-3 col-md-3`).

2021-11-18 16:58 UTC, Mitchel commented on resources/views/app/courses/overview.blade.php
> +                            <li class="list-group-item">Lessons-Chef:<span class="text-primary"> 5</span></li>
De taak kan je zeker splitsen, maar een pull request is dan nog niet persee nodig.

2021-11-18 16:59 UTC, Mitchel commented on resources/views/app/courses/overview.blade.php
> +                            <li class="list-group-item">Lessons-Bartender<span class="text-primary"> 5</span></li>
Benader me er gerust maar voor.

2021-11-18 16:59 UTC, Mitchel commented on resources/views/app/courses/overview.blade.php
> +                            <li class="list-group-item">Lessons-Waiter:<span class="text-primary"> 5</span></li>
Je hebt toen aangegeven dat je filmpjes hebt gekeken en wist hoe het moest.

2021-11-18 16:59 UTC, Mitchel commented on resources/views/app/courses/overview.blade.php
> +                            <h3><input type="text" name="General" value="General" style="border:none;outline: none"></h3>
Deze informatie die je nu ophaalt is alleen om te tonen vanuit de database. Een input is hier dus nog niet nodig.

2021-11-18 17:00 UTC, Mitchel commented on resources/views/app/includes/navigation.blade.php
> +                <i class="fas fa-box"></i> Courses
Ja, maar het moet dan `fal fa-box fa-fw` zijn. Dat is dan jou icoon maar in de juiste stijl.

2021-11-18 17:00 UTC, Mitchel commented on routes/web.php
> +Route::get('-+', [MadeController::class, 'index'])->name('made');
Dat kan niet zomaar uit zichzelf gebeuren.

2021-11-18 17:00 UTC, Mitchel commented on vendor/composer/autoload_real.php
> +        self::$loader = $loader = new \Composer\Autoload\ClassLoader(\dirname(\dirname(__FILE__)));
Dat kan niet zomaar uit zichzelf gebeuren.

2021-11-30 11:24 UTC, Qass11 approved these changes
Ik heb alle codes een door genomen en ik denk dat het goed is, jij was wel lang mee bezig, goed bezig Dani.

2021-11-30 11:41 UTC, Mitchel approved these changes

2021-11-30 11:41 UTC, Mitchel commented on app/Notifications/sendLessonPackageNotification.php
> +            ->line(new HtmlString('<strong>Package name:</strong>' /* . hier gaat de backage naam plaats vinden */))
Omdat je hier nog niks aanroept, gaat het hele systeem fucken.

2021-11-30 11:42 UTC, merged

2021-11-30 11:42 UTC, mohamedloul1 approved these changes
neetjes